[package]
name = "bowling"
version = "0.0.1"
authors = ["Roger Andersen <hexjelly@hexjelly.com>"]

[lib]
name = "bowling"
path = "src/lib.rs"

[dependencies]
failure = "0.1.0"
failure_derive = "0.1.1"
