[package]
name = "bowling"
version = "0.0.1"
authors = ["Roger Andersen <hexjelly@hexjelly.com>"]

[lib]
name = "bowling"
path = "src/lib.rs"

[dependencies]
failure = { git = "https://github.com/withoutboats/failure" }
failure_derive = { git = "https://github.com/withoutboats/failure_derive" }
